info:
  version: @project.version@
spring:
  application:
    name: @project.artifactId@
server:
  port: 7510
logging:
  level:
    root: info
    org.springframework.security: debug
management:
  endpoint:
    health:
      show-details: when_authorized
  endpoints:
    web:
      exposure:
        # 测试使用 - 开放所有端口
        include: "*"

security:
  oauth2:
    resource:
      id: ${spring.application.name}
      jwt:
        key-uri: http://oauth.easycodebox.local:7500/oauth/token_key